const products = [
  {
    id: 1,
    price: 5,
    name: `"ESSENTIALS" CAP`,
    img: "assets/img/catalog/cap1.jpg",
    stock: 10,
    category: "accesory",
  },
  {
    id: 2,
    price: 20,
    name: "MOCHA PARKA",
    img: "assets/img/catalog/parka1.jpg",
    stock: 5,
    category: "parka",
  },
  {
    id: 3,
    price: 14.99,
    name: "NATURE TEE",
    img: "assets/img/catalog/tshirt1.jpg",
    stock: 5,
    category: "tshirt",
  },
  {
    id: 4,
    price: 7,
    name: `"ESSENTIALS" BUCKET CAP`,
    img: "assets/img/catalog/cap2.jpg",
    stock: 3,
    category: "accesory",
  },
  {
    id: 5,
    price: 22,
    name: "NIGHT PARKA",
    img: "assets/img/catalog/parka2.jpg",
    stock: 7,
    category: "parka",
  },
  {
    id: 6,
    price: 9.99,
    name: `"ESSENTIALS" BAG`,
    img: "assets/img/catalog/cap3.jpg",
    stock: 9,
    category: "accesory",
  },
];
